#!/usr/bin/python3
from zipfile import ZipFile
import sys


user_name = sys.argv[1]
path_to_arxiv = sys.argv[2]
path_to_script = sys.argv[3]

with ZipFile(path_to_arxiv,"a") as zip:
    while True:     
        pwd ='/'
        command = input(user_name + '$ ')
        if command != '':
            if command == 'exit':
                break
                zip.close()
            elif command == 'uname':
                print(user_name)
            elif command.split()[0] == 'mkdir':
                new_folder_name = command.split()[1]+ '/'
                zip.writestr(new_folder_name, '')
            elif command == 'ls' :
                for element in zip.namelist() :
                    if(element.endswith('/')):
                        print('dir: ' + element[0:-1])
                    else:
                        print('file: ' + element)
            elif command.split()[0] == 'cd':
                print('uuuuuuuh I cant do this for now')
            else: 
                print('error: unknown command')


